seed: 4
prevent_log_overwrite: True

clip_observations: 5.0
clip_actions: 1.0

policy:
  pi_hid_sizes: [1024, 1024, 512]
  vf_hid_sizes: [1024, 1024, 512]
  activation: elu

learn:
  agent_name: ppo_3obj_releasehold_officialLinearDR_400m_env1024_actor1e4_critic3e4_epoch2_0810
  test: False
  resume: 0
  save_interval: 500
  print_log: True

  # 1024 envs * 8 rollout steps * 48829 iterations = 400,007,168 steps.
  max_iterations: 48829

  cliprange: 0.2
  ent_coef: 0.0
  nsteps: 8
  noptepochs: 2
  nminibatches: 4
  max_grad_norm: 1.0
  optim_stepsize: 1.e-4
  actor_optim_stepsize: 1.e-4
  critic_optim_stepsize: 3.e-4
  schedule: fixed
  desired_kl: 0.01
  gamma: 0.96
  lam: 0.95
  init_noise_std: 0.8
  value_loss_coef: 1.0
  use_clipped_value_loss: True

  log_interval: 1
  asymmetric: False
